name: Project Assignment

on:
  issues:
    types: [ opened, reopened ]
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Open Source Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: 'https://github.com/orgs/SOFware/projects/10'
          github-token: ${{ github.token }}