name: Responsibility Assignment

on:
  issues:
    types: [ reopened ]
  pull_request_target:
    types: [ opened, reopened, converted_to_draft, ready_for_review ]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign'
        uses: toshimaru/auto-author-assign@v2.1.1